services:
  web:
    build: .
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    command: bash -lc "python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6381:6379"

  celery_worker:
    build: .
    env_file:
      - .env
    working_dir: /app/backend
    environment:
      - PYTHONPATH=/app/backend
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    command: celery -A config.celery worker --loglevel=info

volumes:
  postgres_data:
